global:
  scrape_interval: 60s # Інтервал збору метрик за замовчуванням
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'macos-node-exporter'
    static_configs:
      # host.docker.internal дозволяє контейнеру звертатися до хостової macOS
      - targets: ['host.docker.internal:9100']
      